# Site settings
title: Chris's Stuff
email: chris@tembreull.org
description: > # this means to ignore newlines until "baseurl:"
  A place for me to put things and ideas and snippets and stuff I don't want
  to lose track of or forget. Someday, I might just sit and turn this into a
  proper website, but today is not that day.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ctembreull.github.io" # the base hostname & protocol for your site
twitter_username: c2t
github_username:  ctembreull

# Build settings
markdown: kramdown
